#!/usr/bin/env python3
"""Generate native-pixel glyph data from the bundled Emerald font.

The browser never rasterizes these glyphs. Pillow/FreeType renders each supported
size once in monochrome mode, and the application draws the resulting bits on
integer canvas coordinates.
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "public/fonts/pokemon-emerald-gba.woff2"
OUTPUT_PATH = ROOT / "app/emeraldBitmapFont.ts"
FONT_SIZES = (11,)
CHARACTERS = "".join(chr(codepoint) for codepoint in range(32, 127))


def glyph_rows(font: ImageFont.FreeTypeFont, character: str) -> dict[str, object]:
    left, top, right, bottom = font.getbbox(character)
    width = max(0, right - left)
    height = max(0, bottom - top)
    rows: list[int] = []

    if width and height:
        image = Image.new("1", (width, height), 0)
        draw = ImageDraw.Draw(image)
        draw.fontmode = "1"
        draw.text((-left, -top), character, font=font, fill=1)

        for y in range(height):
            bits = 0
            for x in range(width):
                bits = (bits << 1) | int(bool(image.getpixel((x, y))))
            rows.append(bits)

    return {
        "width": width,
        "height": height,
        "xOffset": left,
        "yOffset": top,
        "advance64": round(font.getlength(character) * 64),
        "rows": rows,
    }


def build_font(size: int) -> dict[str, object]:
    font = ImageFont.truetype(str(FONT_PATH), size)
    cap_top = font.getbbox("A")[1]
    glyphs: dict[str, dict[str, object]] = {}
    line_height = 0

    for character in CHARACTERS:
        glyph = glyph_rows(font, character)
        glyph["yOffset"] = int(glyph["yOffset"]) - cap_top
        line_height = max(line_height, int(glyph["yOffset"]) + int(glyph["height"]))
        glyphs[character] = glyph

    return {"size": size, "lineHeight": line_height, "glyphs": glyphs}


def main() -> None:
    fonts = {str(size): build_font(size) for size in FONT_SIZES}
    payload = json.dumps(fonts, ensure_ascii=True, separators=(",", ":"))
    source = f'''// Generated by scripts/generate-emerald-bitmap-font.py. Do not hand-edit.\n\nexport type BitmapGlyph = {{\n  width: number;\n  height: number;\n  xOffset: number;\n  yOffset: number;\n  advance64: number;\n  rows: number[];\n}};\n\nexport type BitmapFont = {{\n  size: number;\n  lineHeight: number;\n  glyphs: Record<string, BitmapGlyph>;\n}};\n\nexport const EMERALD_BITMAP_FONTS: Record<number, BitmapFont> = {payload};\n'''
    OUTPUT_PATH.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
