#!/usr/bin/env python3
"""Generate the deterministic index for historical and current incidents."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HEADING_RE = re.compile(r"^### (?P<incident_id>MTA-[A-Z0-9]+-\d{3}) — (?P<title>.+?)\s*$")
DEFAULT_ARCHIVE = Path("docs/incidents/archive/MISTAKES_TO_AVOID-legacy-20260901.md")
DEFAULT_CURRENT = Path("docs/incidents/current/INCIDENTS.md")
DEFAULT_INDEX = Path("docs/incidents/INDEX.md")


def extract_incidents(archive_path: Path) -> list[tuple[str, str, int]]:
    incidents: list[tuple[str, str, int]] = []
    seen: set[str] = set()
    for line_number, line in enumerate(archive_path.read_text(encoding="utf-8").splitlines(), 1):
        match = HEADING_RE.match(line)
        if match is None:
            continue
        incident_id = match.group("incident_id")
        if incident_id in seen:
            raise ValueError(f"duplicate incident ID: {incident_id}")
        seen.add(incident_id)
        incidents.append((incident_id, match.group("title"), line_number))
    if not incidents:
        raise ValueError(f"no incident headings found in {archive_path}")
    return incidents


def _display_path(path: Path, default: Path) -> str:
    if path.resolve() == default.resolve():
        return default.as_posix()
    return path.as_posix()


def render_index(archive_path: Path, current_path: Path = DEFAULT_CURRENT) -> str:
    sources = ((archive_path, "Historical archive"), (current_path, "Current ledger"))
    incidents: list[tuple[str, str, str, int]] = []
    seen: set[str] = set()
    for source_path, source_name in sources:
        for incident_id, title, line_number in extract_incidents(source_path):
            if incident_id in seen:
                raise ValueError(f"duplicate incident ID: {incident_id}")
            seen.add(incident_id)
            incidents.append((incident_id, title, source_name, line_number))
    rows = [
        "# Incident index",
        "",
        "Generated mechanically from the immutable historical archive and current ledger. Do not edit this file by hand.",
        "",
        f"Historical archive: `{_display_path(archive_path, DEFAULT_ARCHIVE)}`",
        f"Current ledger: `{_display_path(current_path, DEFAULT_CURRENT)}`",
        "",
        "| Incident | Title | Source | Line |",
        "| --- | --- | --- | ---: |",
    ]
    rows.extend(
        f"| `{incident_id}` | {title} | {source_name} | {line_number} |"
        for incident_id, title, source_name, line_number in incidents
    )
    return "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, default=DEFAULT_ARCHIVE)
    parser.add_argument("--current", type=Path, default=DEFAULT_CURRENT)
    parser.add_argument("--index", type=Path, default=DEFAULT_INDEX)
    parser.add_argument("--check", action="store_true", help="fail if the index is stale")
    args = parser.parse_args()

    rendered = render_index(args.archive, args.current)
    if args.check:
        return int(not args.index.exists() or args.index.read_text(encoding="utf-8") != rendered)
    args.index.parent.mkdir(parents=True, exist_ok=True)
    args.index.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
