#!/usr/bin/env python3
"""Generate the deterministic index for the immutable incident archive."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HEADING_RE = re.compile(r"^### (?P<incident_id>MTA-[A-Z0-9]+-\d{3}) — (?P<title>.+?)\s*$")
DEFAULT_ARCHIVE = Path("docs/incidents/archive/MISTAKES_TO_AVOID-legacy-20260901.md")
DEFAULT_INDEX = Path("docs/incidents/INDEX.md")


def extract_incidents(archive_path: Path) -> list[tuple[str, str, int]]:
    incidents: list[tuple[str, str, int]] = []
    seen: set[str] = set()
    for line_number, line in enumerate(archive_path.read_text(encoding="utf-8").splitlines(), 1):
        match = HEADING_RE.match(line)
        if match is None:
            continue
        incident_id = match.group("incident_id")
        if incident_id in seen:
            raise ValueError(f"duplicate incident ID: {incident_id}")
        seen.add(incident_id)
        incidents.append((incident_id, match.group("title"), line_number))
    if not incidents:
        raise ValueError(f"no incident headings found in {archive_path}")
    return incidents


def _display_archive_path(archive_path: Path) -> str:
    if archive_path.resolve() == DEFAULT_ARCHIVE.resolve():
        return DEFAULT_ARCHIVE.as_posix()
    return archive_path.as_posix()


def render_index(archive_path: Path) -> str:
    incidents = extract_incidents(archive_path)
    rows = [
        "# Incident index",
        "",
        "Generated mechanically from the immutable historical archive. Do not edit this file by hand.",
        "",
        f"Source archive: `{_display_archive_path(archive_path)}`",
        "",
        "| Incident | Title | Archive line |",
        "| --- | --- | ---: |",
    ]
    rows.extend(
        f"| `{incident_id}` | {title} | {line_number} |"
        for incident_id, title, line_number in incidents
    )
    return "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, default=DEFAULT_ARCHIVE)
    parser.add_argument("--index", type=Path, default=DEFAULT_INDEX)
    parser.add_argument("--check", action="store_true", help="fail if the index is stale")
    args = parser.parse_args()

    rendered = render_index(args.archive)
    if args.check:
        return int(not args.index.exists() or args.index.read_text(encoding="utf-8") != rendered)
    args.index.parent.mkdir(parents=True, exist_ok=True)
    args.index.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
